version: "3.8"

volumes:
  e_shop_volume:
networks:
  ms_e_shop_network:

services:
  mysql:
    container_name: db_ms_e_shop
    image: mysql:8.0.39
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "6033:3306"
    volumes:
      - e_shop_volume:/var/lib/mysql
      - ./_database/script.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - ms_e_shop_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  php_my_admin:
    container_name: admin_ms_e_shop
    image: phpmyadmin:latest
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3030:80"
    environment:
      PMA_HOST: db_ms_e_shop
    networks:
      - ms_e_shop_network

  ms_authentication_service:
    container_name: authentication-service
    build: ./authentication-service
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db_ms_e_shop/db_ms_authentication_service
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_HIKARI_PASSWORD: root
      SERVER_PORT: 8081
#    ports:
#      - "8081:8081"
    networks:
      - ms_e_shop_network

  ms_product_service:
    container_name: product-service
    build: ./product-service
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://db_ms_e_shop/db_ms_product_service
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: validate
      USERNAME_MYSQL: root
      PASSWORD_MYSQL: root
      QUARKUS_HTTP_PORT: 8082
#    ports:
#      - "8082:8082"
    networks:
      - ms_e_shop_network

  ms_api_gateway:
    container_name: api-gateway
    build: ./api-gateway
    restart: unless-stopped
    depends_on:
      ms_authentication_service:
        condition: service_started
      ms_product_service:
        condition: service_started
    environment:
      AUTHENTICATION_SERVICE_MP_REST_URL: http://authentication-service:8081
      PRODUCT_SERVICE_MP_REST_URL: http://product-service:8082
      # ajouter les autres services
      QUARKUS_HTTP_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - ms_e_shop_network
